version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    env_file: .env
    ports:
      - $PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DATABASE_DATABASENAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
